version: "3.9"

networks:
  caesar_supervisor:
    external: true
    name: caesar_supervisor
  caesar_site:
    external: true
    name: caesar_${SLUG}

services:
  # ---------------
  # MariaDB for the site install
  # - THe Database
  # ---------------
  db:
    image: yobasystems/alpine-mariadb
    container_name: caesar-${SLUG}-db
    volumes:
      - ~/.caesar/db/${SLUG}:/var/lib/mysql
    restart: always
    networks:
      - caesar_supervisor
      - caesar_site
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wp
      MYSQL_USER: wp
      MYSQL_PASSWORD: wp
  # ---------------
  # WordPress Container
  # - WP Core
  # ---------------
  wordpress:
    image: nextpress/caesar-wordpress:0.0.2
    container_name: caesar-${SLUG}-wordpress
    depends_on:
      - caesar-${SLUG}-db
      - caesar-${SLUG}-cert
    networks:
      - caesar_supervisor
      - caesar_site
    volumes:
      - $CWD_PATH/wp:/var/www/html
      - $LIB_PATH/mu-plugins/autoloader.php:/var/www/html/wp-content/mu-plugins/autoloader.php:ro
      - $LIB_PATH/mu-plugins/info.php:/var/www/html/wp-content/mu-plugins/info.php:ro
      - $LIB_PATH/scripts/container:/scripts
      # - $LIB_PATH/htaccess/.htaccess-single:/var/www/html/.htaccess-single
      # - $LIB_PATH/htaccess/.htaccess-subdir:/var/www/html/.htaccess-subdir
      # - $LIB_PATH/htaccess/.htaccess-subdomain:/var/www/html/.htaccess-subdomain
      - $CWD_PATH/wp-content/plugins:/var/www/html/wp-content/plugins
      - $CWD_PATH/wp-content/themes:/var/www/html/wp-content/themes
      - $CWD_PATH/wp-content/mu-plugins:/var/www/html/wp-content/mu-plugins/files
      - $CWD_PATH/logs/xdebug:/logs/xdebug

      # Running Marker
      # Out Products
      - $CWD_PATH/wp-ultimo:/var/www/html/wp-content/plugins/wp-ultimo
      
      # - $CWD_PATH/wp-admin-pages-pro:/var/www/html/wp-content/plugins/wp-admin-pages-pro
      # - $CWD_PATH/material-wp:/var/www/html/wp-content/plugins/material-wp
      # - $CWD_PATH/pro-theme:/var/www/html/wp-content/plugins/pro-theme
    restart: always
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wp
      WORDPRESS_DB_PASSWORD: wp
      WORDPRESS_DB_NAME: wp
      VIRTUAL_HOST: ${DOMAIN_NAME},${ADDITIONAL_DOMAIN_NAMES},${MAPPED_DOMAIN_NAMES}
      VIRTUAL_PORT: 80
  # ---------------
  # Cert Generator
  # - Generates SSL certs.
  # ---------------
  mkcert:
    image: nextpress/caesar-wordpress:0.0.2
    container_name: caesar-${SLUG}-cert
    networks:
      - caesar_supervisor
      - caesar_site
    environment:
      DOMAIN: ${DOMAIN_NAME},${ADDITIONAL_DOMAIN_NAMES},${MAPPED_DOMAIN_NAMES}
    volumes:
      - ~/.caesar/certs:/certs
