version: "3.9"
services:
  db:
    image: yobasystems/alpine-mariadb
    container_name: db
    volumes:
      - $CWD_PATH/volumes/db:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wp
      MYSQL_USER: wp
      MYSQL_PASSWORD: wp
  wordpress:
    container_name: wordpress
    depends_on:
      - db
    image: wordpress:latest
    volumes:
      - $CWD_PATH/wp:/var/www/html
      - $LIB_PATH/mu-plugins/autoloader.php:/var/www/html/wp-content/mu-plugins/autoloader.php
      - $LIB_PATH/scripts/container:/scripts
      - $CWD_PATH/wp-content:/var/www/html/wp-content
      - $CWD_PATH/wp-ultimo:/var/www/html/wp-content/plugins/wp-ultimo
    ports:
      - "8000:80"
    # restart: never
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wp
      WORDPRESS_DB_PASSWORD: wp
      WORDPRESS_DB_NAME: wp
      VIRTUAL_HOST: $DOMAIN_NAME
      VIRTUAL_PORT: 80
  # phpmyadmin:
  #   image: phpmyadmin/phpmyadmin:latest
  #   container_name: phpmyadmin
  #   restart: always
  #   ports:
  #     - "8085:80"
  #   environment:
  #     PMA_USER: pma
  #     PMA_PASSWORD: pma
  #     VIRTUAL_HOST: db.example.com
  #     VIRTUAL_PORT: 85
  #   depends_on:
  #    - db
  nginx-proxy:
    image: nginxproxy/nginx-proxy:alpine
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - $CWD_PATH/certs:/etc/nginx/certs
    depends_on:
     - db
     - wordpress
     - mkcert
  mkcert:
    environment:
      DOMAIN: $DOMAIN_NAME
    container_name: mkcert
    volumes:
      - $CWD_PATH/certs:/certs
    build:
      context: .
volumes:
  wp: {}
  db: {}
  certs: {}